Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.network "private_network", ip: "192.168.33.101"

  config.vm.provision "shell", path: "shell/up.sh"

  config.vm.synced_folder "../../", "/usr/share/nginx/html", \
    :create => true, \
    :owner  => 'vagrant', \
    :group  => 'vagrant', \
    :mount_options => ['dmode=755,fmode=755']

  config.vm.synced_folder "../../tmp", "/usr/share/nginx/html/tmp", \
    :create => true, \
    :owner  => 'nginx', \
    :group  => 'nginx', \
    :mount_options => ['dmode=777,fmode=777']

  config.vm.synced_folder "../../logs", "/usr/share/nginx/html/logs", \
    :create => true, \
    :owner  => 'nginx', \
    :group  => 'nginx', \
    :mount_options => ['dmode=777,fmode=777']
end
